version: '1.0'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db

  node-app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules # Prevent overwriting node_modules
    ports:
      - '8080:3000' # App port
      - '9229:9229' # Debugging port
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - mongo
