version: '1.0'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ../mongo-data:/data/db

  node-app:
    container_name: node-app
    build:
      context: ..
      dockerfile: docker-env/Dockerfile.prod
    ports:
      - '8080:3000'
    environment:
      - NODE_ENV=production
      - TZ=Europe/Berlin
    depends_on:
      - mongo
